// levels.js — 关卡配置

const LEVELS = {
  colors: {
    name: 'Colors',
    icon: '🎨',
    items: [
      { id: 'red',    label: 'RED',    color: '#FF4444', lightColor: '#FF8888', display: '' },
      { id: 'blue',   label: 'BLUE',   color: '#4488FF', lightColor: '#88BBFF', display: '' },
      { id: 'yellow', label: 'YELLOW', color: '#FFD700', lightColor: '#FFED88', display: '' },
      { id: 'green',  label: 'GREEN',  color: '#44CC44', lightColor: '#88EE88', display: '' },
      { id: 'purple', label: 'PURPLE', color: '#AA55FF', lightColor: '#CC99FF', display: '' },
      { id: 'orange', label: 'ORANGE', color: '#FF8833', lightColor: '#FFBB77', display: '' },
      { id: 'pink',   label: 'PINK',   color: '#FF69B4', lightColor: '#FFB0D0', display: '' },
      { id: 'white',  label: 'WHITE',  color: '#F5F5F5', lightColor: '#FFFFFF', display: '' },
      { id: 'black',  label: 'BLACK',  color: '#333333', lightColor: '#555555', display: '' },
      { id: 'brown',  label: 'BROWN',  color: '#8B4513', lightColor: '#CD853F', display: '' },
    ],
    prompt: (item) => `Pop the ${item.id} balloon!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's ${item.id}. Find ${target.id}!`,
  },

  numbers: {
    name: '1-10',
    icon: '🔢',
    items: [
      { id: 'one',      label: '1',  color: '#FF6B6B', lightColor: '#FF9999', display: '1' },
      { id: 'two',      label: '2',  color: '#4ECDC4', lightColor: '#7EDDD7', display: '2' },
      { id: 'three',    label: '3',  color: '#FFD93D', lightColor: '#FFE77A', display: '3' },
      { id: 'four',     label: '4',  color: '#6BCB77', lightColor: '#99DDA2', display: '4' },
      { id: 'five',     label: '5',  color: '#4D96FF', lightColor: '#80B3FF', display: '5' },
      { id: 'six',      label: '6',  color: '#FF6BB5', lightColor: '#FF99CC', display: '6' },
      { id: 'seven',    label: '7',  color: '#9B59B6', lightColor: '#BB8FCE', display: '7' },
      { id: 'eight',    label: '8',  color: '#F39C12', lightColor: '#F7C06B', display: '8' },
      { id: 'nine',     label: '9',  color: '#1ABC9C', lightColor: '#76D7C4', display: '9' },
      { id: 'ten',      label: '10', color: '#E74C3C', lightColor: '#F1948A', display: '10' },
    ],
    prompt: (item) => `Find number ${item.display}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's ${item.id}. Find ${target.id}!`,
  },

  numbers2: {
    name: '11-20',
    icon: '🔟',
    items: [
      { id: 'eleven',   label: '11', color: '#8E44AD', lightColor: '#AF7AC5', display: '11' },
      { id: 'twelve',   label: '12', color: '#2ECC71', lightColor: '#82E0AA', display: '12' },
      { id: 'thirteen', label: '13', color: '#E67E22', lightColor: '#F0B27A', display: '13' },
      { id: 'fourteen', label: '14', color: '#3498DB', lightColor: '#85C1E9', display: '14' },
      { id: 'fifteen',  label: '15', color: '#E91E63', lightColor: '#F48FB1', display: '15' },
      { id: 'sixteen',  label: '16', color: '#00BCD4', lightColor: '#80DEEA', display: '16' },
      { id: 'seventeen',label: '17', color: '#FF5722', lightColor: '#FF8A65', display: '17' },
      { id: 'eighteen', label: '18', color: '#607D8B', lightColor: '#90A4AE', display: '18' },
      { id: 'nineteen', label: '19', color: '#795548', lightColor: '#A1887F', display: '19' },
      { id: 'twenty',   label: '20', color: '#FF4081', lightColor: '#FF80AB', display: '20' },
    ],
    prompt: (item) => `Find number ${item.display}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's ${item.id}. Find ${target.id}!`,
  },

  animals: {
    name: 'Animals',
    icon: '🐾',
    items: [
      { id: 'cat',      label: 'CAT',      color: '#FF8833', lightColor: '#FFBB77', display: 'assets/images/animals/cat.svg' },
      { id: 'dog',      label: 'DOG',      color: '#8B4513', lightColor: '#CD853F', display: 'assets/images/animals/dog.svg' },
      { id: 'fish',     label: 'FISH',     color: '#4488FF', lightColor: '#88BBFF', display: 'assets/images/animals/fish.svg' },
      { id: 'bird',     label: 'BIRD',     color: '#44CC44', lightColor: '#88EE88', display: 'assets/images/animals/bird.svg' },
      { id: 'elephant', label: 'ELEPHANT', color: '#888888', lightColor: '#BBBBBB', display: 'assets/images/animals/elephant.svg' },
      { id: 'lion',     label: 'LION',     color: '#FFD700', lightColor: '#FFED88', display: 'assets/images/animals/lion.svg' },
      { id: 'rabbit',   label: 'RABBIT',   color: '#FFB0D0', lightColor: '#FFD4E8', display: 'assets/images/animals/rabbit.svg' },
      { id: 'monkey',   label: 'MONKEY',   color: '#CD853F', lightColor: '#DEB887', display: 'assets/images/animals/monkey.svg' },
      { id: 'duck',     label: 'DUCK',     color: '#FFD700', lightColor: '#FFED88', display: 'assets/images/animals/duck.svg' },
      { id: 'bear',     label: 'BEAR',     color: '#8B4513', lightColor: '#A0522D', display: 'assets/images/animals/bear.svg' },
      { id: 'cow',      label: 'COW',      color: '#F5F5F5', lightColor: '#FFFFFF', display: 'assets/images/animals/cow.svg' },
      { id: 'pig',      label: 'PIG',      color: '#FFB6C1', lightColor: '#FFD4E0', display: 'assets/images/animals/pig.svg' },
      { id: 'horse',    label: 'HORSE',    color: '#8B4513', lightColor: '#A0522D', display: 'assets/images/animals/horse.svg' },
      { id: 'sheep',    label: 'SHEEP',    color: '#F5F5F5', lightColor: '#FFFFFF', display: 'assets/images/animals/sheep.svg' },
      { id: 'frog',     label: 'FROG',     color: '#44CC44', lightColor: '#88EE88', display: 'assets/images/animals/frog.svg' },
      { id: 'penguin',  label: 'PENGUIN',  color: '#333333', lightColor: '#555555', display: 'assets/images/animals/penguin.svg' },
      { id: 'owl',      label: 'OWL',      color: '#8B4513', lightColor: '#CD853F', display: 'assets/images/animals/owl.svg' },
      { id: 'turtle',   label: 'TURTLE',   color: '#44CC44', lightColor: '#88EE88', display: 'assets/images/animals/turtle.svg' },
    ],
    prompt: (item) => `Find the ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's a ${item.id}. Find the ${target.id}!`,
  },

  shapes: {
    name: 'Shapes',
    icon: '🔷',
    items: [
      { id: 'circle',    label: 'CIRCLE',    color: '#FF6B6B', lightColor: '#FF9999', display: 'assets/images/shapes/circle.svg' },
      { id: 'square',    label: 'SQUARE',    color: '#4488FF', lightColor: '#88BBFF', display: 'assets/images/shapes/square.svg' },
      { id: 'triangle',  label: 'TRIANGLE',  color: '#FFD700', lightColor: '#FFED88', display: 'assets/images/shapes/triangle.svg' },
      { id: 'star',      label: 'STAR',      color: '#FF8833', lightColor: '#FFBB77', display: 'assets/images/shapes/star.svg' },
      { id: 'heart',     label: 'HEART',     color: '#FF69B4', lightColor: '#FFB0D0', display: 'assets/images/shapes/heart.svg' },
      { id: 'diamond',   label: 'DIAMOND',   color: '#AA55FF', lightColor: '#CC99FF', display: 'assets/images/shapes/diamond.svg' },
      { id: 'oval',      label: 'OVAL',      color: '#4ECDC4', lightColor: '#7EDDD7', display: 'assets/images/shapes/oval.svg' },
      { id: 'rectangle', label: 'RECTANGLE', color: '#6BCB77', lightColor: '#99DDA2', display: 'assets/images/shapes/rectangle.svg' },
      { id: 'pentagon',  label: 'PENTAGON',  color: '#E91E63', lightColor: '#F48FB1', display: 'assets/images/shapes/pentagon.svg' },
      { id: 'hexagon',   label: 'HEXAGON',   color: '#FF5722', lightColor: '#FF8A65', display: 'assets/images/shapes/hexagon.svg' },
    ],
    prompt: (item) => `Find the ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's a ${item.id}. Find the ${target.id}!`,
  },

  body: {
    name: 'Body',
    icon: '🖐️',
    items: [
      { id: 'hand',   label: 'HAND',   color: '#FFD700', lightColor: '#FFED88', display: 'assets/images/body/hand.svg' },
      { id: 'foot',   label: 'FOOT',   color: '#8B4513', lightColor: '#CD853F', display: 'assets/images/body/foot.svg' },
      { id: 'eye',    label: 'EYE',    color: '#4488FF', lightColor: '#88BBFF', display: 'assets/images/body/eye.svg' },
      { id: 'ear',    label: 'EAR',    color: '#FF8833', lightColor: '#FFBB77', display: 'assets/images/body/ear.svg' },
      { id: 'nose',   label: 'NOSE',   color: '#FF6B6B', lightColor: '#FF9999', display: 'assets/images/body/nose.svg' },
      { id: 'mouth',  label: 'MOUTH',  color: '#FF4444', lightColor: '#FF8888', display: 'assets/images/body/mouth.svg' },
      { id: 'head',   label: 'HEAD',   color: '#FFB0D0', lightColor: '#FFD4E8', display: 'assets/images/body/head.svg' },
      { id: 'teeth',  label: 'TEETH',  color: '#F5F5F5', lightColor: '#FFFFFF', display: 'assets/images/body/teeth.svg' },
      { id: 'hair',   label: 'HAIR',   color: '#333333', lightColor: '#555555', display: 'assets/images/body/hair.svg' },
      { id: 'tummy',  label: 'TUMMY',  color: '#FFD700', lightColor: '#FFED88', display: 'assets/images/body/tummy.svg' },
    ],
    prompt: (item) => `Find the ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's ${item.id}. Find the ${target.id}!`,
  },

  fruits: {
    name: 'Fruits',
    icon: '🍎',
    items: [
      { id: 'apple',      label: 'APPLE',      color: '#FF4444', lightColor: '#FF8888', display: 'assets/images/food/apple.svg' },
      { id: 'banana',     label: 'BANANA',     color: '#FFD700', lightColor: '#FFED88', display: 'assets/images/food/banana.svg' },
      { id: 'watermelon', label: 'WATERMELON', color: '#44CC44', lightColor: '#88EE88', display: 'assets/images/food/watermelon.svg' },
      { id: 'strawberry', label: 'STRAWBERRY', color: '#FF4444', lightColor: '#FF8888', display: 'assets/images/food/strawberry.svg' },
      { id: 'grape',      label: 'GRAPE',      color: '#AA55FF', lightColor: '#CC99FF', display: '🍇' },
      { id: 'orange',     label: 'ORANGE',     color: '#FF8833', lightColor: '#FFBB77', display: '🍊' },
      { id: 'peach',      label: 'PEACH',      color: '#FFB0D0', lightColor: '#FFD4E8', display: '🍑' },
      { id: 'cherry',     label: 'CHERRY',     color: '#FF4444', lightColor: '#FF8888', display: '🍒' },
      { id: 'pear',       label: 'PEAR',       color: '#6BCB77', lightColor: '#99DDA2', display: '🍐' },
      { id: 'pineapple',  label: 'PINEAPPLE',  color: '#FFD700', lightColor: '#FFED88', display: '🍍' },
      { id: 'mango',      label: 'MANGO',      color: '#FF8833', lightColor: '#FFBB77', display: '🥭' },
      { id: 'lemon',      label: 'LEMON',      color: '#FFD700', lightColor: '#FFED88', display: '🍋' },
    ],
    prompt: (item) => `Find the ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's a ${item.id}. Find the ${target.id}!`,
  },

  vegetables: {
    name: 'Vegetables',
    icon: '🥕',
    items: [
      { id: 'carrot',     label: 'CARROT',     color: '#FF8833', lightColor: '#FFBB77', display: 'assets/images/food/carrot.svg' },
      { id: 'tomato',     label: 'TOMATO',     color: '#FF4444', lightColor: '#FF8888', display: '🍅' },
      { id: 'potato',     label: 'POTATO',     color: '#DEB887', lightColor: '#F5DEB3', display: '🥔' },
      { id: 'corn',       label: 'CORN',       color: '#FFD700', lightColor: '#FFED88', display: '🌽' },
      { id: 'broccoli',   label: 'BROCCOLI',   color: '#44CC44', lightColor: '#88EE88', display: '🥦' },
      { id: 'pea',        label: 'PEA',        color: '#44CC44', lightColor: '#88EE88', display: '🟢' },
      { id: 'onion',      label: 'ONION',      color: '#DEB887', lightColor: '#F5DEB3', display: '🧅' },
      { id: 'cucumber',   label: 'CUCUMBER',   color: '#44CC44', lightColor: '#88EE88', display: '🥒' },
      { id: 'pumpkin',    label: 'PUMPKIN',    color: '#FF8833', lightColor: '#FFBB77', display: '🎃' },
      { id: 'mushroom',   label: 'MUSHROOM',   color: '#DEB887', lightColor: '#F5DEB3', display: '🍄' },
    ],
    prompt: (item) => `Find the ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's a ${item.id}. Find the ${target.id}!`,
  },

  food: {
    name: 'Food',
    icon: '🍕',
    items: [
      { id: 'bread',      label: 'BREAD',      color: '#DEB887', lightColor: '#F5DEB3', display: 'assets/images/food/bread.svg' },
      { id: 'egg',        label: 'EGG',        color: '#FFEFD5', lightColor: '#FFF8DC', display: 'assets/images/food/egg.svg' },
      { id: 'cake',       label: 'CAKE',       color: '#FF69B4', lightColor: '#FFB0D0', display: 'assets/images/food/cake.svg' },
      { id: 'cookie',     label: 'COOKIE',     color: '#CD853F', lightColor: '#DEB887', display: 'assets/images/food/cookie.svg' },
      { id: 'cheese',     label: 'CHEESE',     color: '#FFD700', lightColor: '#FFED88', display: 'assets/images/food/cheese.svg' },
      { id: 'pizza',      label: 'PIZZA',      color: '#FF8833', lightColor: '#FFBB77', display: 'assets/images/food/pizza.svg' },
      { id: 'milk',       label: 'MILK',       color: '#F5F5F5', lightColor: '#FFFFFF', display: 'assets/images/food/milk.svg' },
      { id: 'juice',      label: 'JUICE',      color: '#FF8833', lightColor: '#FFBB77', display: 'assets/images/breakfast/juice.svg' },
      { id: 'cereal',     label: 'CEREAL',     color: '#FFD700', lightColor: '#FFED88', display: 'assets/images/breakfast/cereal.svg' },
      { id: 'pancake',    label: 'PANCAKE',    color: '#DEB887', lightColor: '#F5DEB3', display: 'assets/images/breakfast/pancake.svg' },
      { id: 'rice',       label: 'RICE',       color: '#F5F5F5', lightColor: '#FFFFFF', display: '🍚' },
      { id: 'noodle',     label: 'NOODLE',     color: '#FFD700', lightColor: '#FFED88', display: '🍜' },
      { id: 'ice cream',  label: 'ICE CREAM',  color: '#FFB0D0', lightColor: '#FFD4E8', display: '🍦' },
      { id: 'chocolate',  label: 'CHOCOLATE',  color: '#8B4513', lightColor: '#CD853F', display: '🍫' },
    ],
    prompt: (item) => `Find the ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's ${item.id}. Find the ${target.id}!`,
  },

  vehicles: {
    name: 'Vehicles',
    icon: '🚗',
    items: [
      { id: 'car',        label: 'CAR',        color: '#FF4444', lightColor: '#FF8888', display: 'assets/images/vehicles/car.svg' },
      { id: 'bus',        label: 'BUS',        color: '#FFD700', lightColor: '#FFED88', display: 'assets/images/vehicles/bus.svg' },
      { id: 'train',      label: 'TRAIN',      color: '#4488FF', lightColor: '#88BBFF', display: 'assets/images/vehicles/train.svg' },
      { id: 'airplane',   label: 'AIRPLANE',   color: '#87CEEB', lightColor: '#B0E0FF', display: 'assets/images/vehicles/airplane.svg' },
      { id: 'bicycle',    label: 'BICYCLE',    color: '#FF8833', lightColor: '#FFBB77', display: 'assets/images/vehicles/bicycle.svg' },
      { id: 'boat',       label: 'BOAT',       color: '#4488FF', lightColor: '#88BBFF', display: 'assets/images/vehicles/boat.svg' },
      { id: 'helicopter', label: 'HELICOPTER', color: '#FF6B6B', lightColor: '#FF9999', display: 'assets/images/vehicles/helicopter.svg' },
      { id: 'fire truck', label: 'FIRE TRUCK', color: '#FF4444', lightColor: '#FF8888', display: 'assets/images/vehicles/firetruck.svg' },
    ],
    prompt: (item) => `Find the ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's a ${item.id}. Find the ${target.id}!`,
  },

  community: {
    name: 'Helpers',
    icon: '👨‍🚒',
    items: [
      { id: 'firefighter', label: 'FIREFIGHTER', color: '#FF4444', lightColor: '#FF8888', display: 'assets/images/community/firefighter.svg' },
      { id: 'doctor',      label: 'DOCTOR',      color: '#87CEEB', lightColor: '#B0E0FF', display: 'assets/images/community/doctor.svg' },
      { id: 'teacher',     label: 'TEACHER',     color: '#44CC44', lightColor: '#88EE88', display: 'assets/images/community/teacher.svg' },
      { id: 'police',      label: 'POLICE',      color: '#4488FF', lightColor: '#88BBFF', display: 'assets/images/community/police.svg' },
      { id: 'chef',        label: 'CHEF',        color: '#F5F5F5', lightColor: '#FFFFFF', display: 'assets/images/community/chef.svg' },
      { id: 'farmer',      label: 'FARMER',      color: '#44CC44', lightColor: '#88EE88', display: 'assets/images/community/farmer.svg' },
      { id: 'astronaut',   label: 'ASTRONAUT',   color: '#F5F5F5', lightColor: '#FFFFFF', display: 'assets/images/community/astronaut.svg' },
      { id: 'pilot',       label: 'PILOT',       color: '#4488FF', lightColor: '#88BBFF', display: 'assets/images/community/pilot.svg' },
    ],
    prompt: (item) => `Find the ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's a ${item.id}. Find the ${target.id}!`,
  },

  daily: {
    name: 'Daily Life',
    icon: '🏠',
    items: [
      { id: 'elevator',   label: 'ELEVATOR',   color: '#888888', lightColor: '#BBBBBB', display: 'assets/images/daily/elevator.svg' },
      { id: 'stairs',     label: 'STAIRS',     color: '#8B4513', lightColor: '#CD853F', display: 'assets/images/daily/stairs.svg' },
      { id: 'door',       label: 'DOOR',       color: '#8B4513', lightColor: '#CD853F', display: 'assets/images/daily/door.svg' },
      { id: 'window',     label: 'WINDOW',     color: '#87CEEB', lightColor: '#B0E0FF', display: 'assets/images/daily/window.svg' },
      { id: 'bed',        label: 'BED',        color: '#4488FF', lightColor: '#88BBFF', display: 'assets/images/daily/bed.svg' },
      { id: 'bathtub',    label: 'BATHTUB',    color: '#87CEEB', lightColor: '#B0E0FF', display: 'assets/images/daily/bathtub.svg' },
      { id: 'toilet',     label: 'TOILET',     color: '#F5F5F5', lightColor: '#FFFFFF', display: 'assets/images/daily/toilet.svg' },
      { id: 'toothbrush', label: 'TOOTHBRUSH', color: '#4488FF', lightColor: '#88BBFF', display: 'assets/images/daily/toothbrush.svg' },
    ],
    prompt: (item) => `Find the ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's a ${item.id}. Find the ${target.id}!`,
  },

  weather: {
    name: 'Weather',
    icon: '☀️',
    items: [
      { id: 'sun',     label: 'SUN',     color: '#FFD700', lightColor: '#FFED88', display: 'assets/images/weather/sun.svg' },
      { id: 'rain',    label: 'RAIN',    color: '#4488FF', lightColor: '#88BBFF', display: 'assets/images/weather/rain.svg' },
      { id: 'snow',    label: 'SNOW',    color: '#87CEEB', lightColor: '#B0E0FF', display: 'assets/images/weather/snow.svg' },
      { id: 'cloud',   label: 'CLOUD',   color: '#CCCCCC', lightColor: '#EEEEEE', display: 'assets/images/weather/cloud.svg' },
      { id: 'rainbow', label: 'RAINBOW', color: '#FF6B6B', lightColor: '#FF9999', display: 'assets/images/weather/rainbow.svg' },
      { id: 'wind',    label: 'WIND',    color: '#87CEEB', lightColor: '#B0E0FF', display: 'assets/images/weather/wind.svg' },
      { id: 'thunder', label: 'THUNDER', color: '#FFD700', lightColor: '#FFED88', display: 'assets/images/weather/thunder.svg' },
      { id: 'moon',    label: 'MOON',    color: '#FFD700', lightColor: '#FFED88', display: 'assets/images/weather/moon.svg' },
    ],
    prompt: (item) => `Find the ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's ${item.id}. Find the ${target.id}!`,
  },

  clothing: {
    name: 'Clothing',
    icon: '👕',
    items: [
      { id: 'hat',     label: 'HAT',     color: '#FF4444', lightColor: '#FF8888', display: 'assets/images/clothing/hat.svg' },
      { id: 'shoes',   label: 'SHOES',   color: '#4488FF', lightColor: '#88BBFF', display: 'assets/images/clothing/shoes.svg' },
      { id: 'shirt',   label: 'SHIRT',   color: '#44CC44', lightColor: '#88EE88', display: 'assets/images/clothing/shirt.svg' },
      { id: 'pants',   label: 'PANTS',   color: '#4488FF', lightColor: '#88BBFF', display: 'assets/images/clothing/pants.svg' },
      { id: 'socks',   label: 'SOCKS',   color: '#FF8833', lightColor: '#FFBB77', display: 'assets/images/clothing/socks.svg' },
      { id: 'jacket',  label: 'JACKET',  color: '#FF6B6B', lightColor: '#FF9999', display: 'assets/images/clothing/jacket.svg' },
      { id: 'dress',   label: 'DRESS',   color: '#FF69B4', lightColor: '#FFB0D0', display: 'assets/images/clothing/dress.svg' },
      { id: 'glasses', label: 'GLASSES', color: '#333333', lightColor: '#555555', display: 'assets/images/clothing/glasses.svg' },
    ],
    prompt: (item) => `Find the ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's ${item.id}. Find the ${target.id}!`,
  },

  emotions: {
    name: 'Feelings',
    icon: '😊',
    items: [
      { id: 'happy',   label: 'HAPPY',   color: '#FFD700', lightColor: '#FFED88', display: 'assets/images/emotions/happy.svg' },
      { id: 'sad',     label: 'SAD',     color: '#4488FF', lightColor: '#88BBFF', display: 'assets/images/emotions/sad.svg' },
      { id: 'angry',   label: 'ANGRY',   color: '#FF4444', lightColor: '#FF8888', display: 'assets/images/emotions/angry.svg' },
      { id: 'scared',  label: 'SCARED',  color: '#AA55FF', lightColor: '#CC99FF', display: 'assets/images/emotions/scared.svg' },
      { id: 'sleepy',  label: 'SLEEPY',  color: '#9B59B6', lightColor: '#BB8FCE', display: 'assets/images/emotions/sleepy.svg' },
      { id: 'excited', label: 'EXCITED', color: '#FF8833', lightColor: '#FFBB77', display: 'assets/images/emotions/excited.svg' },
      { id: 'love',    label: 'LOVE',    color: '#FF69B4', lightColor: '#FFB0D0', display: 'assets/images/emotions/love.svg' },
      { id: 'silly',   label: 'SILLY',   color: '#44CC44', lightColor: '#88EE88', display: 'assets/images/emotions/silly.svg' },
    ],
    prompt: (item) => `Find the ${item.id} face!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's ${item.id}. Find ${target.id}!`,
  },

  home: {
    name: 'Home',
    icon: '🏡',
    items: [
      { id: 'table', label: 'TABLE', color: '#8B4513', lightColor: '#CD853F', display: 'assets/images/home/table.svg' },
      { id: 'chair', label: 'CHAIR', color: '#DEB887', lightColor: '#F5DEB3', display: 'assets/images/home/chair.svg' },
      { id: 'lamp',  label: 'LAMP',  color: '#FFD700', lightColor: '#FFED88', display: 'assets/images/home/lamp.svg' },
      { id: 'clock', label: 'CLOCK', color: '#4488FF', lightColor: '#88BBFF', display: 'assets/images/home/clock.svg' },
      { id: 'tv',    label: 'TV',    color: '#333333', lightColor: '#555555', display: 'assets/images/home/tv.svg' },
      { id: 'phone', label: 'PHONE', color: '#333333', lightColor: '#555555', display: 'assets/images/home/phone.svg' },
      { id: 'book',  label: 'BOOK',  color: '#FF6B6B', lightColor: '#FF9999', display: 'assets/images/home/book.svg' },
      { id: 'cup',   label: 'CUP',   color: '#4ECDC4', lightColor: '#7EDDD7', display: 'assets/images/home/cup.svg' },
    ],
    prompt: (item) => `Find the ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's a ${item.id}. Find the ${target.id}!`,
  },
};
