// levels.js — 关卡配置

const LEVELS = {
  colors: {
    name: 'Colors',
    icon: '🎨',
    items: [
      { id: 'red',    label: 'RED',    color: '#FF4444', lightColor: '#FF8888', display: '' },
      { id: 'blue',   label: 'BLUE',   color: '#4488FF', lightColor: '#88BBFF', display: '' },
      { id: 'yellow', label: 'YELLOW', color: '#FFD700', lightColor: '#FFED88', display: '' },
      { id: 'green',  label: 'GREEN',  color: '#44CC44', lightColor: '#88EE88', display: '' },
      { id: 'purple', label: 'PURPLE', color: '#AA55FF', lightColor: '#CC99FF', display: '' },
      { id: 'orange', label: 'ORANGE', color: '#FF8833', lightColor: '#FFBB77', display: '' },
      { id: 'pink',   label: 'PINK',   color: '#FF69B4', lightColor: '#FFB0D0', display: '' },
    ],
    prompt: (item) => `Pop the ${item.id} balloon!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's ${item.id}. Find ${target.id}!`,
  },

  numbers: {
    name: 'Numbers',
    icon: '🔢',
    items: [
      { id: 'one',      label: '1',  color: '#FF6B6B', lightColor: '#FF9999', display: '1' },
      { id: 'two',      label: '2',  color: '#4ECDC4', lightColor: '#7EDDD7', display: '2' },
      { id: 'three',    label: '3',  color: '#FFD93D', lightColor: '#FFE77A', display: '3' },
      { id: 'four',     label: '4',  color: '#6BCB77', lightColor: '#99DDA2', display: '4' },
      { id: 'five',     label: '5',  color: '#4D96FF', lightColor: '#80B3FF', display: '5' },
      { id: 'six',      label: '6',  color: '#FF6BB5', lightColor: '#FF99CC', display: '6' },
      { id: 'seven',    label: '7',  color: '#9B59B6', lightColor: '#BB8FCE', display: '7' },
      { id: 'eight',    label: '8',  color: '#F39C12', lightColor: '#F7C06B', display: '8' },
      { id: 'nine',     label: '9',  color: '#1ABC9C', lightColor: '#76D7C4', display: '9' },
      { id: 'ten',      label: '10', color: '#E74C3C', lightColor: '#F1948A', display: '10' },
      { id: 'eleven',   label: '11', color: '#8E44AD', lightColor: '#AF7AC5', display: '11' },
      { id: 'twelve',   label: '12', color: '#2ECC71', lightColor: '#82E0AA', display: '12' },
      { id: 'thirteen', label: '13', color: '#E67E22', lightColor: '#F0B27A', display: '13' },
      { id: 'fourteen', label: '14', color: '#3498DB', lightColor: '#85C1E9', display: '14' },
      { id: 'fifteen',  label: '15', color: '#E91E63', lightColor: '#F48FB1', display: '15' },
      { id: 'sixteen',  label: '16', color: '#00BCD4', lightColor: '#80DEEA', display: '16' },
      { id: 'seventeen',label: '17', color: '#FF5722', lightColor: '#FF8A65', display: '17' },
      { id: 'eighteen', label: '18', color: '#607D8B', lightColor: '#90A4AE', display: '18' },
      { id: 'nineteen', label: '19', color: '#795548', lightColor: '#A1887F', display: '19' },
      { id: 'twenty',   label: '20', color: '#FF4081', lightColor: '#FF80AB', display: '20' },
    ],
    prompt: (item) => `Find number ${item.display}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's ${item.id}. Find ${target.id}!`,
  },

  /* === 以下关卡暂时隐藏 ===
  shapes: {
    name: 'Shapes',
    icon: '🔷',
    items: [
      { id: 'circle',   label: 'CIRCLE',   color: '#FF6B6B', lightColor: '#FF9999', display: '🔴' },
      { id: 'square',   label: 'SQUARE',   color: '#4488FF', lightColor: '#88BBFF', display: '🟦' },
      { id: 'triangle', label: 'TRIANGLE', color: '#FFD700', lightColor: '#FFED88', display: '📐' },
      { id: 'star',     label: 'STAR',     color: '#FF8833', lightColor: '#FFBB77', display: '⭐' },
      { id: 'heart',    label: 'HEART',    color: '#FF69B4', lightColor: '#FFB0D0', display: '❤️' },
      { id: 'diamond',  label: 'DIAMOND',  color: '#AA55FF', lightColor: '#CC99FF', display: '💎' },
    ],
    prompt: (item) => `Find the ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's a ${item.id}. Find the ${target.id}!`,
  },

  animals: {
    name: 'Animals',
    icon: '🐾',
    items: [
      { id: 'cat',      label: 'CAT',      color: '#FF8833', lightColor: '#FFBB77', display: '🐱' },
      { id: 'dog',      label: 'DOG',      color: '#8B4513', lightColor: '#CD853F', display: '🐶' },
      { id: 'fish',     label: 'FISH',     color: '#4488FF', lightColor: '#88BBFF', display: '🐟' },
      { id: 'bird',     label: 'BIRD',     color: '#44CC44', lightColor: '#88EE88', display: '🐦' },
      { id: 'elephant', label: 'ELEPHANT', color: '#888888', lightColor: '#BBBBBB', display: '🐘' },
      { id: 'lion',     label: 'LION',     color: '#FFD700', lightColor: '#FFED88', display: '🦁' },
      { id: 'rabbit',   label: 'RABBIT',   color: '#FFB0D0', lightColor: '#FFD4E8', display: '🐰' },
      { id: 'monkey',   label: 'MONKEY',   color: '#CD853F', lightColor: '#DEB887', display: '🐵' },
      { id: 'duck',     label: 'DUCK',     color: '#FFD700', lightColor: '#FFED88', display: '🦆' },
      { id: 'bear',     label: 'BEAR',     color: '#8B4513', lightColor: '#A0522D', display: '🐻' },
    ],
    prompt: (item) => `Find the ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's a ${item.id}. Find the ${target.id}!`,
  },

  actions: {
    name: 'Actions',
    icon: '🏃',
    items: [
      { id: 'jump',    label: 'JUMP',    color: '#FF6B6B', lightColor: '#FF9999', display: '🦘' },
      { id: 'clap',    label: 'CLAP',    color: '#FFD700', lightColor: '#FFED88', display: '👏' },
      { id: 'wave',    label: 'WAVE',    color: '#4488FF', lightColor: '#88BBFF', display: '👋' },
      { id: 'dance',   label: 'DANCE',   color: '#FF69B4', lightColor: '#FFB0D0', display: '💃' },
      { id: 'run',     label: 'RUN',     color: '#44CC44', lightColor: '#88EE88', display: '🏃' },
      { id: 'swim',    label: 'SWIM',    color: '#4ECDC4', lightColor: '#7EDDD7', display: '🏊' },
      { id: 'eat',     label: 'EAT',     color: '#FF8833', lightColor: '#FFBB77', display: '🍽️' },
      { id: 'sleep',   label: 'SLEEP',   color: '#AA55FF', lightColor: '#CC99FF', display: '😴' },
    ],
    prompt: (item) => `Find ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's ${item.id}. Find ${target.id}!`,
  },

  greetings: {
    name: 'Greetings',
    icon: '👋',
    items: [
      { id: 'hello',      label: 'HELLO',      color: '#FFD700', lightColor: '#FFED88', display: '👋' },
      { id: 'bye bye',    label: 'BYE BYE',    color: '#4488FF', lightColor: '#88BBFF', display: '🫡' },
      { id: 'thank you',  label: 'THANK YOU',  color: '#FF69B4', lightColor: '#FFB0D0', display: '🙏' },
      { id: 'please',     label: 'PLEASE',     color: '#44CC44', lightColor: '#88EE88', display: '🤲' },
      { id: 'sorry',      label: 'SORRY',      color: '#AA55FF', lightColor: '#CC99FF', display: '😢' },
      { id: 'yes',        label: 'YES',        color: '#6BCB77', lightColor: '#99DDA2', display: '✅' },
      { id: 'no',         label: 'NO',         color: '#FF4444', lightColor: '#FF8888', display: '❌' },
      { id: 'I love you', label: 'I LOVE YOU', color: '#FF6B6B', lightColor: '#FF9999', display: '❤️' },
    ],
    prompt: (item) => `Find ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's ${item.id}. Find ${target.id}!`,
  },

  food: {
    name: 'Food',
    icon: '🍎',
    items: [
      { id: 'apple',     label: 'APPLE',     color: '#FF4444', lightColor: '#FF8888', display: '🍎' },
      { id: 'banana',    label: 'BANANA',    color: '#FFD700', lightColor: '#FFED88', display: '🍌' },
      { id: 'milk',      label: 'MILK',      color: '#FFFFFF', lightColor: '#F5F5F5', display: '🥛' },
      { id: 'bread',     label: 'BREAD',     color: '#DEB887', lightColor: '#F5DEB3', display: '🍞' },
      { id: 'egg',       label: 'EGG',       color: '#FFEFD5', lightColor: '#FFF8DC', display: '🥚' },
      { id: 'water',     label: 'WATER',     color: '#4488FF', lightColor: '#88BBFF', display: '💧' },
      { id: 'cake',      label: 'CAKE',      color: '#FF69B4', lightColor: '#FFB0D0', display: '🎂' },
      { id: 'cookie',    label: 'COOKIE',    color: '#CD853F', lightColor: '#DEB887', display: '🍪' },
    ],
    prompt: (item) => `Find the ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's ${item.id}. Find the ${target.id}!`,
  },

  body: {
    name: 'Body',
    icon: '🖐️',
    items: [
      { id: 'hand',   label: 'HAND',   color: '#FFD700', lightColor: '#FFED88', display: '🖐️' },
      { id: 'foot',   label: 'FOOT',   color: '#8B4513', lightColor: '#CD853F', display: '🦶' },
      { id: 'head',   label: 'HEAD',   color: '#FFB0D0', lightColor: '#FFD4E8', display: '🗣️' },
      { id: 'eye',    label: 'EYE',    color: '#4488FF', lightColor: '#88BBFF', display: '👁️' },
      { id: 'ear',    label: 'EAR',    color: '#FF8833', lightColor: '#FFBB77', display: '👂' },
      { id: 'nose',   label: 'NOSE',   color: '#FF6B6B', lightColor: '#FF9999', display: '👃' },
      { id: 'mouth',  label: 'MOUTH',  color: '#FF4444', lightColor: '#FF8888', display: '👄' },
      { id: 'tummy',  label: 'TUMMY',  color: '#FFD700', lightColor: '#FFED88', display: '🫃' },
    ],
    prompt: (item) => `Find the ${item.id}!`,
    correctSay: (item) => item.id,
    wrongSay: (item, target) => `That's ${item.id}. Find the ${target.id}!`,
  },
  === 隐藏结束 === */
};
